// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASKZPATGlBCTY5Rt7_lySmfecrOGYJyec',
    appId: '1:913051510921:web:a1d6aff272278a760fbe58',
    messagingSenderId: '913051510921',
    projectId: 'fir-crud-basics-a32db',
    authDomain: 'fir-crud-basics-a32db.firebaseapp.com',
    storageBucket: 'fir-crud-basics-a32db.firebasestorage.app',
    measurementId: 'G-THT5DK6587',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlJFdPYvy7GiCCU52I4hMDsTmut9RR9c',
    appId: '1:913051510921:android:8824d5fd18a478760fbe58',
    messagingSenderId: '913051510921',
    projectId: 'fir-crud-basics-a32db',
    storageBucket: 'fir-crud-basics-a32db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuMmLpSkkZugPXWY3UbHQE7_ODwLNOMkY',
    appId: '1:913051510921:ios:3c89da87b40b83220fbe58',
    messagingSenderId: '913051510921',
    projectId: 'fir-crud-basics-a32db',
    storageBucket: 'fir-crud-basics-a32db.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuMmLpSkkZugPXWY3UbHQE7_ODwLNOMkY',
    appId: '1:913051510921:ios:3c89da87b40b83220fbe58',
    messagingSenderId: '913051510921',
    projectId: 'fir-crud-basics-a32db',
    storageBucket: 'fir-crud-basics-a32db.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASKZPATGlBCTY5Rt7_lySmfecrOGYJyec',
    appId: '1:913051510921:web:170d8e308dada8b30fbe58',
    messagingSenderId: '913051510921',
    projectId: 'fir-crud-basics-a32db',
    authDomain: 'fir-crud-basics-a32db.firebaseapp.com',
    storageBucket: 'fir-crud-basics-a32db.firebasestorage.app',
    measurementId: 'G-DY1HV413SY',
  );
}
